/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.31")
    id("org.springframework.boot").version("2.1.7.RELEASE")
    id ("org.jetbrains.kotlin.plugin.jpa").version("1.3.41")

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.springframework.boot:spring-boot-starter-web:2.1.7.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.1.7.RELEASE")

    compileOnly("javax.xml.bind:jaxb-api:2.3.0")
    runtime("org.springframework.boot:spring-boot-devtools:2.1.7.RELEASE")
    runtime("com.h2database:h2:1.4.199")

    compileOnly("com.graphql-java:graphql-java:11.0")
    compileOnly("com.graphql-java:graphql-java-tools:5.2.4")
    compileOnly("com.graphql-java:graphql-java-servlet:6.1.3")
    implementation("com.graphql-java:graphql-spring-boot-starter:5.0.2")

//   Dev Only
    compileOnly("com.graphql-java:graphiql-spring-boot-starter:5.0.2")

    compileOnly("io.reactivex.rxjava2:rxjava:2.2.3")
}

application {
    // Define the main class for the application
    mainClassName = "graphql.examples.DiveIntoGraphqlInJavaApplication"
}
